name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Solidity Example
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Format
        run: yarn run check-pretty
      - name: Lint
        run: |
          yarn run lint-sol
          yarn run lint-es
      - name: Compile
        run: |
          yarn run compile-sol
          yarn run compile-ts
      - name: Test
        env:
          ALCHEMY_ETHEREUM_MAINNET_TOKEN: ${{ secrets.ALCHEMY_ETHEREUM_MAINNET_TOKEN }}
        run: yarn run test
