name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Format
        run: yarn run check-pretty
      - name: Lint
        run: |
          yarn run lint-sol
          yarn run lint-es
      - name: Compile
        run: |
          yarn run compile-sol
          yarn run compile-ts
